/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 car.glb --transform --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    uploads_files_313735_MercedesML233: THREE.Mesh
    uploads_files_313735_MercedesML233_1: THREE.Mesh
    uploads_files_313735_MercedesML420: THREE.Mesh
    uploads_files_313735_MercedesML420_1: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
}

export function Car(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[4.635, 1.882, 1.542]} rotation={[0.001, 0, 0]} scale={0.021}>
        <mesh geometry={nodes.uploads_files_313735_MercedesML233.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.uploads_files_313735_MercedesML233_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[0.644, 2.171, -1.866]} rotation={[0.001, 0, 0]} scale={0.021}>
        <mesh geometry={nodes.uploads_files_313735_MercedesML420.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.uploads_files_313735_MercedesML420_1.geometry} material={materials.PaletteMaterial004} />
      </group>
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
