/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 rolex.glb --transform --types
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle014: THREE.Mesh;
    Circle: THREE.Mesh;
    Circle004: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle008: THREE.Mesh;
    Circle009: THREE.Mesh;
    Circle027: THREE.Mesh;
    Plane007: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    meetal: THREE.MeshStandardMaterial;
    ["meetal.001"]: THREE.MeshStandardMaterial;
    ["meetal.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["glossy black.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
};

export function Rolex(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/rolex-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      {/* <mesh
        geometry={nodes.Circle014.geometry}
        material={materials.PaletteMaterial001}
      /> */}
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.meetal}
        position={[0.02, 0.053, 0.003]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["meetal.001"]}
        position={[0.011, 0.052, 0.003]}
        rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials.PaletteMaterial001}
        position={[0.011, 0.052, 0.003]}
        rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        scale={[0.021, 0.019, 0.021]}
      />
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials["meetal.002"]}
        position={[0.011, 0.052, 0.003]}
        rotation={[Math.PI / 2, 0.254, -Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle007.geometry}
        material={materials["Material.003"]}
        position={[0.02, 0.053, 0.003]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle008.geometry}
        material={materials["glossy black.001"]}
        position={[0.02, 0.054, 0.003]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle009.geometry}
        material={materials.PaletteMaterial002}
        position={[0.02, 0.053, 0.003]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Circle027.geometry}
        material={materials["Material.001"]}
        position={[0.02, 0.054, 0.003]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={1}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.PaletteMaterial003}
        position={[0.023, 0.054, -0.01]}
        rotation={[-Math.PI / 2, -0.254, Math.PI / 2]}
        scale={[-0.004, 0.005, 0.004]}
      />
    </group>
  );
}

useGLTF.preload("/rolex-transformed.glb");
